=== venkataramanavgit/Ep-Practical/task1/WebContent/student2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students_info (student+)>
<!ELEMENT student (regno,name,avg,dob,time,mobileno,distinction)>
<!ELEMENT regno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT avg (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT mobileno (#PCDATA)>
<!ELEMENT distinction (#PCDATA)>

=== venkataramanavgit/Ep-Practical/task1/WebContent/student2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students_info SYSTEM "student2.dtd">

<students_info>

<student>                               

   <regno>190</regno>

   <name>venkat</name>   

   <avg>92</avg>

   <dob>15-08-2000</dob> 

   <time>10:30 AM</time>      

   <mobileno>9849989977</mobileno>                        

   <distinction>YES</distinction>

 </student>
 <student>                               

   <regno>191</regno>

   <name>BHARATH</name>   

   <avg>91</avg>

   <dob>1-03-2001</dob> 

   <time>10:30 AM</time>      

   <mobileno>9849948900</mobileno>                       

   <distinction>YES</distinction>

 </student>
 <student>                               

   <regno>192</regno>

   <name>SWAMY</name>   

   <avg>92</avg>

   <dob>15-06-2001</dob> 

   <time>10:30 AM</time>      

   <mobileno>9849984900</mobileno>                         

   <distinction>YES</distinction>

 </student>
 <student>                               

   <regno>193</regno>

   <name>AMAN</name>   

   <avg>93</avg>

   <dob>11-06-2002</dob> 

   <time>10:30 AM</time>      

   <mobileno>9848984900</mobileno>                         

   <distinction>YES</distinction>

 </student>
 <student>                               

   <regno>194</regno>

   <name>DINESH</name>   

   <avg>94</avg>

   <dob>20-10-2002</dob> 

   <time>10:30 AM</time>      

   <mobileno>9349984900</mobileno>                         

   <distinction>YES</distinction>

 </student>
</students_info>
